using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Seclai.Models;

/// <summary>An EMAIL_RECEIVED trigger's resolved address(es) and config.</summary>
public sealed class EmailTriggerConfigResponse
{
    [JsonPropertyName("agent_id")]
    public string AgentId { get; set; } = string.Empty;

    [JsonPropertyName("email_addresses")]
    public List<string>? EmailAddresses { get; set; }

    [JsonPropertyName("email_alias")]
    public string? EmailAlias { get; set; }

    [JsonPropertyName("email_allowed_senders")]
    public List<string>? EmailAllowedSenders { get; set; }

    [JsonPropertyName("email_ignore_auto_generated")]
    public bool? EmailIgnoreAutoGenerated { get; set; }

    [JsonPropertyName("email_queue_on_quota")]
    public bool? EmailQueueOnQuota { get; set; }

    [JsonPropertyName("email_require_sender_auth")]
    public bool? EmailRequireSenderAuth { get; set; }

    [JsonPropertyName("trigger_id")]
    public string TriggerId { get; set; } = string.Empty;

    [JsonPropertyName("trigger_type")]
    public string TriggerType { get; set; } = string.Empty;
}
