using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Seclai.Models;

/// <summary>Alias and/or sender allowlist for an EMAIL_RECEIVED trigger. A field omitted is left unchanged; passing ``null`` (or ``""`` for ``alias``) clears it.</summary>
public sealed class SetEmailTriggerConfigRequest
{
    /// <summary>Custom alias for the address `&lt;alias&gt;.&lt;accountID&gt;@agent.seclai.com` (alphanumeric plus '+', '.', '-'; 1–32 chars; not starting/ending with '+', '.', '-'; not UUID-shaped). Pass null/empty to clear.</summary>
    [JsonPropertyName("alias")]
    public string? Alias { get; set; }

    /// <summary>Allowlist of full sender addresses and/or bare domains (a bare domain also matches sub-domains). Empty/null accepts any sender.</summary>
    [JsonPropertyName("allowed_senders")]
    public List<string>? AllowedSenders { get; set; }

    /// <summary>When true (default for new triggers), machine-generated inbound mail (auto-replies, bulk/list mail, bounces) is dropped before a run to prevent auto-reply loops. Set false to process automated mail.</summary>
    [JsonPropertyName("ignore_auto_generated")]
    public bool? IgnoreAutoGenerated { get; set; }

    /// <summary>When true (default false), inbound mail that exceeds the account's hourly email-trigger rate is parked in a QUEUED run and drained later by the catch-up sweep instead of being failed; when false, over-rate mail fails immediately.</summary>
    [JsonPropertyName("queue_on_quota")]
    public bool? QueueOnQuota { get; set; }

    /// <summary>When true (default for new triggers), the envelope sender must pass SPF or DMARC even on an open inbox (no allowlist); unauthenticated, spoofable mail is rejected. Set false to accept fully unauthenticated mail on an open inbox.</summary>
    [JsonPropertyName("require_sender_auth")]
    public bool? RequireSenderAuth { get; set; }
}
