using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Seclai.Models;

/// <summary>
/// Alias, sender allowlist and inbound-handling flags for an EMAIL_RECEIVED trigger.
/// </summary>
/// <remarks>
/// A property left <c>null</c> is omitted from the request and the server leaves that
/// field unchanged. To clear a field, send its empty value: <c>""</c> for
/// <see cref="Alias"/>, an empty list for <see cref="AllowedSenders"/>.
/// </remarks>
public sealed class SetEmailTriggerConfigRequest
{
    /// <summary>Custom alias for the address <c>&lt;alias&gt;.&lt;accountID&gt;@agent.seclai.com</c> (alphanumeric plus '+', '.', '-'; 1–32 chars; not starting/ending with '+', '.', '-'; not UUID-shaped). Send <c>""</c> to clear; leave null to keep the current alias.</summary>
    [JsonPropertyName("alias")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Alias { get; set; }

    /// <summary>Allowlist of full sender addresses and/or bare domains (a bare domain also matches sub-domains). Empty/null accepts any sender.</summary>
    [JsonPropertyName("allowed_senders")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<string>? AllowedSenders { get; set; }

    /// <summary>When true (default for new triggers), machine-generated inbound mail (auto-replies, bulk/list mail, bounces) is dropped before a run to prevent auto-reply loops. Set false to process automated mail.</summary>
    [JsonPropertyName("ignore_auto_generated")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? IgnoreAutoGenerated { get; set; }

    /// <summary>When true (default false), inbound mail that exceeds the account's hourly email-trigger rate is parked in a QUEUED run and drained later by the catch-up sweep instead of being failed; when false, over-rate mail fails immediately.</summary>
    [JsonPropertyName("queue_on_quota")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? QueueOnQuota { get; set; }

    /// <summary>When true (default for new triggers), the envelope sender must pass SPF or DMARC even on an open inbox (no allowlist); unauthenticated, spoofable mail is rejected. Set false to accept fully unauthenticated mail on an open inbox.</summary>
    [JsonPropertyName("require_sender_auth")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? RequireSenderAuth { get; set; }
}
