"""Regenerate GatedListEndpoints.txt from the backend's version-gated list call sites.

    python3 tests/Seclai.Tests/gated_list_endpoints.py ../seclai/backend/api/src/api/routers/api \
        > tests/Seclai.Tests/GatedListEndpoints.txt

Prints one `METHOD /path` per call to versioned_list_response,
versioned_offset_list_response or versioned_complete_list_response: the enclosing
route decorator joined to the file's APIRouter prefix, without the leading /api.
"""
import glob
import re
import sys

CALL = re.compile(r"\bversioned_(?:offset_|complete_)?list_response\(")
ROUTE = re.compile(r'@router\.(get|post|put|patch|delete)\(\s*"([^"]*)"')
PREFIX = re.compile(r'APIRouter\([^)]*prefix="([^"]+)"', re.S)


def routes(root: str) -> list[str]:
    found = []
    for path in sorted(glob.glob(root.rstrip("/") + "/*.py")):
        text = open(path).read()
        prefix = PREFIX.search(text)
        if not prefix:
            continue
        for call in CALL.finditer(text):
            line_start = text.rfind("\n", 0, call.start()) + 1
            if "import" in text[line_start:call.start()]:
                continue
            decorators = list(ROUTE.finditer(text, 0, call.start()))
            if not decorators:
                raise SystemExit(f"{path}: no route decorator above offset {call.start()}")
            verb, sub = decorators[-1].groups()
            full = (prefix.group(1) + sub).removeprefix("/api").rstrip("/")
            found.append(f"{verb.upper()} {full}")
    return sorted(found)


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    print("# Generated by gated_list_endpoints.py from the backend's version-gated list call sites. Do not edit by hand.")
    print("\n".join(routes(sys.argv[1])))
